/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SellerPanelRouteImport } from './routes/seller-panel'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as AuthVerifiedRouteImport } from './routes/auth.verified'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthenticatedSellerRouteImport } from './routes/_authenticated/seller'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedSellerIndexRouteImport } from './routes/_authenticated/seller.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedSellerWithdrawalsRouteImport } from './routes/_authenticated/seller.withdrawals'
import { Route as AuthenticatedSellerWalletRouteImport } from './routes/_authenticated/seller.wallet'
import { Route as AuthenticatedSellerVerificationRouteImport } from './routes/_authenticated/seller.verification'
import { Route as AuthenticatedSellerTransactionsRouteImport } from './routes/_authenticated/seller.transactions'
import { Route as AuthenticatedSellerSupportRouteImport } from './routes/_authenticated/seller.support'
import { Route as AuthenticatedSellerStoreRouteImport } from './routes/_authenticated/seller.store'
import { Route as AuthenticatedSellerSettingsRouteImport } from './routes/_authenticated/seller.settings'
import { Route as AuthenticatedSellerSecurityRouteImport } from './routes/_authenticated/seller.security'
import { Route as AuthenticatedSellerReviewsRouteImport } from './routes/_authenticated/seller.reviews'
import { Route as AuthenticatedSellerOrdersRouteImport } from './routes/_authenticated/seller.orders'
import { Route as AuthenticatedSellerNotificationsRouteImport } from './routes/_authenticated/seller.notifications'
import { Route as AuthenticatedSellerMessagesRouteImport } from './routes/_authenticated/seller.messages'
import { Route as AuthenticatedSellerListingsRouteImport } from './routes/_authenticated/seller.listings'
import { Route as AuthenticatedSellerEarningsRouteImport } from './routes/_authenticated/seller.earnings'
import { Route as AuthenticatedSellerDisputesRouteImport } from './routes/_authenticated/seller.disputes'
import { Route as AuthenticatedSellerDeliveryRouteImport } from './routes/_authenticated/seller.delivery'
import { Route as AuthenticatedSellerCouponsRouteImport } from './routes/_authenticated/seller.coupons'
import { Route as AuthenticatedSellerBoostsRouteImport } from './routes/_authenticated/seller.boosts'
import { Route as AuthenticatedSellerAnalyticsRouteImport } from './routes/_authenticated/seller.analytics'
import { Route as AuthenticatedSellerAdsRouteImport } from './routes/_authenticated/seller.ads'
import { Route as AuthenticatedCheckoutVerifyPaymentRouteImport } from './routes/_authenticated/checkout.verify-payment'
import { Route as AuthenticatedCheckoutPaymentRouteImport } from './routes/_authenticated/checkout.payment'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminSubscriptionsRouteImport } from './routes/_authenticated/admin.subscriptions'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin.payments'
import { Route as AuthenticatedAdminListingsRouteImport } from './routes/_authenticated/admin.listings'
import { Route as AuthenticatedAdminDisputesRouteImport } from './routes/_authenticated/admin.disputes'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin.categories'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedSellerSubscriptionIndexRouteImport } from './routes/_authenticated/seller.subscription.index'
import { Route as AuthenticatedSellerSubscriptionPaymentRouteImport } from './routes/_authenticated/seller.subscription.payment'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerPanelRoute = SellerPanelRouteImport.update({
  id: '/seller-panel',
  path: '/seller-panel',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifiedRoute = AuthVerifiedRouteImport.update({
  id: '/auth/verified',
  path: '/auth/verified',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSellerRoute = AuthenticatedSellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSellerIndexRoute =
  AuthenticatedSellerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedSellerWithdrawalsRoute =
  AuthenticatedSellerWithdrawalsRouteImport.update({
    id: '/withdrawals',
    path: '/withdrawals',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerWalletRoute =
  AuthenticatedSellerWalletRouteImport.update({
    id: '/wallet',
    path: '/wallet',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerVerificationRoute =
  AuthenticatedSellerVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerTransactionsRoute =
  AuthenticatedSellerTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerSupportRoute =
  AuthenticatedSellerSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerStoreRoute =
  AuthenticatedSellerStoreRouteImport.update({
    id: '/store',
    path: '/store',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerSettingsRoute =
  AuthenticatedSellerSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerSecurityRoute =
  AuthenticatedSellerSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerReviewsRoute =
  AuthenticatedSellerReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerOrdersRoute =
  AuthenticatedSellerOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerNotificationsRoute =
  AuthenticatedSellerNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerMessagesRoute =
  AuthenticatedSellerMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerListingsRoute =
  AuthenticatedSellerListingsRouteImport.update({
    id: '/listings',
    path: '/listings',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerEarningsRoute =
  AuthenticatedSellerEarningsRouteImport.update({
    id: '/earnings',
    path: '/earnings',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerDisputesRoute =
  AuthenticatedSellerDisputesRouteImport.update({
    id: '/disputes',
    path: '/disputes',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerDeliveryRoute =
  AuthenticatedSellerDeliveryRouteImport.update({
    id: '/delivery',
    path: '/delivery',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerCouponsRoute =
  AuthenticatedSellerCouponsRouteImport.update({
    id: '/coupons',
    path: '/coupons',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerBoostsRoute =
  AuthenticatedSellerBoostsRouteImport.update({
    id: '/boosts',
    path: '/boosts',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerAnalyticsRoute =
  AuthenticatedSellerAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerAdsRoute = AuthenticatedSellerAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AuthenticatedSellerRoute,
} as any)
const AuthenticatedCheckoutVerifyPaymentRoute =
  AuthenticatedCheckoutVerifyPaymentRouteImport.update({
    id: '/checkout/verify-payment',
    path: '/checkout/verify-payment',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCheckoutPaymentRoute =
  AuthenticatedCheckoutPaymentRouteImport.update({
    id: '/checkout/payment',
    path: '/checkout/payment',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSubscriptionsRoute =
  AuthenticatedAdminSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminListingsRoute =
  AuthenticatedAdminListingsRouteImport.update({
    id: '/listings',
    path: '/listings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDisputesRoute =
  AuthenticatedAdminDisputesRouteImport.update({
    id: '/disputes',
    path: '/disputes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedSellerSubscriptionIndexRoute =
  AuthenticatedSellerSubscriptionIndexRouteImport.update({
    id: '/subscription/',
    path: '/subscription/',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerSubscriptionPaymentRoute =
  AuthenticatedSellerSubscriptionPaymentRouteImport.update({
    id: '/subscription/payment',
    path: '/subscription/payment',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/seller-panel': typeof SellerPanelRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/seller': typeof AuthenticatedSellerRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/verified': typeof AuthVerifiedRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/disputes': typeof AuthenticatedAdminDisputesRoute
  '/admin/listings': typeof AuthenticatedAdminListingsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/checkout/payment': typeof AuthenticatedCheckoutPaymentRoute
  '/checkout/verify-payment': typeof AuthenticatedCheckoutVerifyPaymentRoute
  '/seller/ads': typeof AuthenticatedSellerAdsRoute
  '/seller/analytics': typeof AuthenticatedSellerAnalyticsRoute
  '/seller/boosts': typeof AuthenticatedSellerBoostsRoute
  '/seller/coupons': typeof AuthenticatedSellerCouponsRoute
  '/seller/delivery': typeof AuthenticatedSellerDeliveryRoute
  '/seller/disputes': typeof AuthenticatedSellerDisputesRoute
  '/seller/earnings': typeof AuthenticatedSellerEarningsRoute
  '/seller/listings': typeof AuthenticatedSellerListingsRoute
  '/seller/messages': typeof AuthenticatedSellerMessagesRoute
  '/seller/notifications': typeof AuthenticatedSellerNotificationsRoute
  '/seller/orders': typeof AuthenticatedSellerOrdersRoute
  '/seller/reviews': typeof AuthenticatedSellerReviewsRoute
  '/seller/security': typeof AuthenticatedSellerSecurityRoute
  '/seller/settings': typeof AuthenticatedSellerSettingsRoute
  '/seller/store': typeof AuthenticatedSellerStoreRoute
  '/seller/support': typeof AuthenticatedSellerSupportRoute
  '/seller/transactions': typeof AuthenticatedSellerTransactionsRoute
  '/seller/verification': typeof AuthenticatedSellerVerificationRoute
  '/seller/wallet': typeof AuthenticatedSellerWalletRoute
  '/seller/withdrawals': typeof AuthenticatedSellerWithdrawalsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/seller/': typeof AuthenticatedSellerIndexRoute
  '/seller/subscription/payment': typeof AuthenticatedSellerSubscriptionPaymentRoute
  '/seller/subscription/': typeof AuthenticatedSellerSubscriptionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/seller-panel': typeof SellerPanelRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/verified': typeof AuthVerifiedRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/disputes': typeof AuthenticatedAdminDisputesRoute
  '/admin/listings': typeof AuthenticatedAdminListingsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/checkout/payment': typeof AuthenticatedCheckoutPaymentRoute
  '/checkout/verify-payment': typeof AuthenticatedCheckoutVerifyPaymentRoute
  '/seller/ads': typeof AuthenticatedSellerAdsRoute
  '/seller/analytics': typeof AuthenticatedSellerAnalyticsRoute
  '/seller/boosts': typeof AuthenticatedSellerBoostsRoute
  '/seller/coupons': typeof AuthenticatedSellerCouponsRoute
  '/seller/delivery': typeof AuthenticatedSellerDeliveryRoute
  '/seller/disputes': typeof AuthenticatedSellerDisputesRoute
  '/seller/earnings': typeof AuthenticatedSellerEarningsRoute
  '/seller/listings': typeof AuthenticatedSellerListingsRoute
  '/seller/messages': typeof AuthenticatedSellerMessagesRoute
  '/seller/notifications': typeof AuthenticatedSellerNotificationsRoute
  '/seller/orders': typeof AuthenticatedSellerOrdersRoute
  '/seller/reviews': typeof AuthenticatedSellerReviewsRoute
  '/seller/security': typeof AuthenticatedSellerSecurityRoute
  '/seller/settings': typeof AuthenticatedSellerSettingsRoute
  '/seller/store': typeof AuthenticatedSellerStoreRoute
  '/seller/support': typeof AuthenticatedSellerSupportRoute
  '/seller/transactions': typeof AuthenticatedSellerTransactionsRoute
  '/seller/verification': typeof AuthenticatedSellerVerificationRoute
  '/seller/wallet': typeof AuthenticatedSellerWalletRoute
  '/seller/withdrawals': typeof AuthenticatedSellerWithdrawalsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/seller': typeof AuthenticatedSellerIndexRoute
  '/seller/subscription/payment': typeof AuthenticatedSellerSubscriptionPaymentRoute
  '/seller/subscription': typeof AuthenticatedSellerSubscriptionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/seller-panel': typeof SellerPanelRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/seller': typeof AuthenticatedSellerRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/verified': typeof AuthVerifiedRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$id': typeof ProductIdRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/disputes': typeof AuthenticatedAdminDisputesRoute
  '/_authenticated/admin/listings': typeof AuthenticatedAdminListingsRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/checkout/payment': typeof AuthenticatedCheckoutPaymentRoute
  '/_authenticated/checkout/verify-payment': typeof AuthenticatedCheckoutVerifyPaymentRoute
  '/_authenticated/seller/ads': typeof AuthenticatedSellerAdsRoute
  '/_authenticated/seller/analytics': typeof AuthenticatedSellerAnalyticsRoute
  '/_authenticated/seller/boosts': typeof AuthenticatedSellerBoostsRoute
  '/_authenticated/seller/coupons': typeof AuthenticatedSellerCouponsRoute
  '/_authenticated/seller/delivery': typeof AuthenticatedSellerDeliveryRoute
  '/_authenticated/seller/disputes': typeof AuthenticatedSellerDisputesRoute
  '/_authenticated/seller/earnings': typeof AuthenticatedSellerEarningsRoute
  '/_authenticated/seller/listings': typeof AuthenticatedSellerListingsRoute
  '/_authenticated/seller/messages': typeof AuthenticatedSellerMessagesRoute
  '/_authenticated/seller/notifications': typeof AuthenticatedSellerNotificationsRoute
  '/_authenticated/seller/orders': typeof AuthenticatedSellerOrdersRoute
  '/_authenticated/seller/reviews': typeof AuthenticatedSellerReviewsRoute
  '/_authenticated/seller/security': typeof AuthenticatedSellerSecurityRoute
  '/_authenticated/seller/settings': typeof AuthenticatedSellerSettingsRoute
  '/_authenticated/seller/store': typeof AuthenticatedSellerStoreRoute
  '/_authenticated/seller/support': typeof AuthenticatedSellerSupportRoute
  '/_authenticated/seller/transactions': typeof AuthenticatedSellerTransactionsRoute
  '/_authenticated/seller/verification': typeof AuthenticatedSellerVerificationRoute
  '/_authenticated/seller/wallet': typeof AuthenticatedSellerWalletRoute
  '/_authenticated/seller/withdrawals': typeof AuthenticatedSellerWithdrawalsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/seller/': typeof AuthenticatedSellerIndexRoute
  '/_authenticated/seller/subscription/payment': typeof AuthenticatedSellerSubscriptionPaymentRoute
  '/_authenticated/seller/subscription/': typeof AuthenticatedSellerSubscriptionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/blog'
    | '/careers'
    | '/categories'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/orders'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/seller-panel'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/admin'
    | '/seller'
    | '/auth/callback'
    | '/auth/verified'
    | '/category/$slug'
    | '/product/$id'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/disputes'
    | '/admin/listings'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/checkout/payment'
    | '/checkout/verify-payment'
    | '/seller/ads'
    | '/seller/analytics'
    | '/seller/boosts'
    | '/seller/coupons'
    | '/seller/delivery'
    | '/seller/disputes'
    | '/seller/earnings'
    | '/seller/listings'
    | '/seller/messages'
    | '/seller/notifications'
    | '/seller/orders'
    | '/seller/reviews'
    | '/seller/security'
    | '/seller/settings'
    | '/seller/store'
    | '/seller/support'
    | '/seller/transactions'
    | '/seller/verification'
    | '/seller/wallet'
    | '/seller/withdrawals'
    | '/admin/'
    | '/seller/'
    | '/seller/subscription/payment'
    | '/seller/subscription/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/blog'
    | '/careers'
    | '/categories'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/orders'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/seller-panel'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/auth/callback'
    | '/auth/verified'
    | '/category/$slug'
    | '/product/$id'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/disputes'
    | '/admin/listings'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/checkout/payment'
    | '/checkout/verify-payment'
    | '/seller/ads'
    | '/seller/analytics'
    | '/seller/boosts'
    | '/seller/coupons'
    | '/seller/delivery'
    | '/seller/disputes'
    | '/seller/earnings'
    | '/seller/listings'
    | '/seller/messages'
    | '/seller/notifications'
    | '/seller/orders'
    | '/seller/reviews'
    | '/seller/security'
    | '/seller/settings'
    | '/seller/store'
    | '/seller/support'
    | '/seller/transactions'
    | '/seller/verification'
    | '/seller/wallet'
    | '/seller/withdrawals'
    | '/admin'
    | '/seller'
    | '/seller/subscription/payment'
    | '/seller/subscription'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/account'
    | '/blog'
    | '/careers'
    | '/categories'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/orders'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/seller-panel'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/_authenticated/admin'
    | '/_authenticated/seller'
    | '/auth/callback'
    | '/auth/verified'
    | '/category/$slug'
    | '/product/$id'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/disputes'
    | '/_authenticated/admin/listings'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/subscriptions'
    | '/_authenticated/admin/users'
    | '/_authenticated/checkout/payment'
    | '/_authenticated/checkout/verify-payment'
    | '/_authenticated/seller/ads'
    | '/_authenticated/seller/analytics'
    | '/_authenticated/seller/boosts'
    | '/_authenticated/seller/coupons'
    | '/_authenticated/seller/delivery'
    | '/_authenticated/seller/disputes'
    | '/_authenticated/seller/earnings'
    | '/_authenticated/seller/listings'
    | '/_authenticated/seller/messages'
    | '/_authenticated/seller/notifications'
    | '/_authenticated/seller/orders'
    | '/_authenticated/seller/reviews'
    | '/_authenticated/seller/security'
    | '/_authenticated/seller/settings'
    | '/_authenticated/seller/store'
    | '/_authenticated/seller/support'
    | '/_authenticated/seller/transactions'
    | '/_authenticated/seller/verification'
    | '/_authenticated/seller/wallet'
    | '/_authenticated/seller/withdrawals'
    | '/_authenticated/admin/'
    | '/_authenticated/seller/'
    | '/_authenticated/seller/subscription/payment'
    | '/_authenticated/seller/subscription/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  BlogRoute: typeof BlogRoute
  CareersRoute: typeof CareersRoute
  CategoriesRoute: typeof CategoriesRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SellerPanelRoute: typeof SellerPanelRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthVerifiedRoute: typeof AuthVerifiedRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller-panel': {
      id: '/seller-panel'
      path: '/seller-panel'
      fullPath: '/seller-panel'
      preLoaderRoute: typeof SellerPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verified': {
      id: '/auth/verified'
      path: '/auth/verified'
      fullPath: '/auth/verified'
      preLoaderRoute: typeof AuthVerifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/seller': {
      id: '/_authenticated/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof AuthenticatedSellerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/seller/': {
      id: '/_authenticated/seller/'
      path: '/'
      fullPath: '/seller/'
      preLoaderRoute: typeof AuthenticatedSellerIndexRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/seller/withdrawals': {
      id: '/_authenticated/seller/withdrawals'
      path: '/withdrawals'
      fullPath: '/seller/withdrawals'
      preLoaderRoute: typeof AuthenticatedSellerWithdrawalsRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/wallet': {
      id: '/_authenticated/seller/wallet'
      path: '/wallet'
      fullPath: '/seller/wallet'
      preLoaderRoute: typeof AuthenticatedSellerWalletRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/verification': {
      id: '/_authenticated/seller/verification'
      path: '/verification'
      fullPath: '/seller/verification'
      preLoaderRoute: typeof AuthenticatedSellerVerificationRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/transactions': {
      id: '/_authenticated/seller/transactions'
      path: '/transactions'
      fullPath: '/seller/transactions'
      preLoaderRoute: typeof AuthenticatedSellerTransactionsRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/support': {
      id: '/_authenticated/seller/support'
      path: '/support'
      fullPath: '/seller/support'
      preLoaderRoute: typeof AuthenticatedSellerSupportRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/store': {
      id: '/_authenticated/seller/store'
      path: '/store'
      fullPath: '/seller/store'
      preLoaderRoute: typeof AuthenticatedSellerStoreRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/settings': {
      id: '/_authenticated/seller/settings'
      path: '/settings'
      fullPath: '/seller/settings'
      preLoaderRoute: typeof AuthenticatedSellerSettingsRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/security': {
      id: '/_authenticated/seller/security'
      path: '/security'
      fullPath: '/seller/security'
      preLoaderRoute: typeof AuthenticatedSellerSecurityRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/reviews': {
      id: '/_authenticated/seller/reviews'
      path: '/reviews'
      fullPath: '/seller/reviews'
      preLoaderRoute: typeof AuthenticatedSellerReviewsRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/orders': {
      id: '/_authenticated/seller/orders'
      path: '/orders'
      fullPath: '/seller/orders'
      preLoaderRoute: typeof AuthenticatedSellerOrdersRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/notifications': {
      id: '/_authenticated/seller/notifications'
      path: '/notifications'
      fullPath: '/seller/notifications'
      preLoaderRoute: typeof AuthenticatedSellerNotificationsRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/messages': {
      id: '/_authenticated/seller/messages'
      path: '/messages'
      fullPath: '/seller/messages'
      preLoaderRoute: typeof AuthenticatedSellerMessagesRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/listings': {
      id: '/_authenticated/seller/listings'
      path: '/listings'
      fullPath: '/seller/listings'
      preLoaderRoute: typeof AuthenticatedSellerListingsRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/earnings': {
      id: '/_authenticated/seller/earnings'
      path: '/earnings'
      fullPath: '/seller/earnings'
      preLoaderRoute: typeof AuthenticatedSellerEarningsRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/disputes': {
      id: '/_authenticated/seller/disputes'
      path: '/disputes'
      fullPath: '/seller/disputes'
      preLoaderRoute: typeof AuthenticatedSellerDisputesRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/delivery': {
      id: '/_authenticated/seller/delivery'
      path: '/delivery'
      fullPath: '/seller/delivery'
      preLoaderRoute: typeof AuthenticatedSellerDeliveryRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/coupons': {
      id: '/_authenticated/seller/coupons'
      path: '/coupons'
      fullPath: '/seller/coupons'
      preLoaderRoute: typeof AuthenticatedSellerCouponsRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/boosts': {
      id: '/_authenticated/seller/boosts'
      path: '/boosts'
      fullPath: '/seller/boosts'
      preLoaderRoute: typeof AuthenticatedSellerBoostsRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/analytics': {
      id: '/_authenticated/seller/analytics'
      path: '/analytics'
      fullPath: '/seller/analytics'
      preLoaderRoute: typeof AuthenticatedSellerAnalyticsRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/ads': {
      id: '/_authenticated/seller/ads'
      path: '/ads'
      fullPath: '/seller/ads'
      preLoaderRoute: typeof AuthenticatedSellerAdsRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/checkout/verify-payment': {
      id: '/_authenticated/checkout/verify-payment'
      path: '/checkout/verify-payment'
      fullPath: '/checkout/verify-payment'
      preLoaderRoute: typeof AuthenticatedCheckoutVerifyPaymentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checkout/payment': {
      id: '/_authenticated/checkout/payment'
      path: '/checkout/payment'
      fullPath: '/checkout/payment'
      preLoaderRoute: typeof AuthenticatedCheckoutPaymentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/subscriptions': {
      id: '/_authenticated/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AuthenticatedAdminSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/listings': {
      id: '/_authenticated/admin/listings'
      path: '/listings'
      fullPath: '/admin/listings'
      preLoaderRoute: typeof AuthenticatedAdminListingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/disputes': {
      id: '/_authenticated/admin/disputes'
      path: '/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AuthenticatedAdminDisputesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/seller/subscription/': {
      id: '/_authenticated/seller/subscription/'
      path: '/subscription'
      fullPath: '/seller/subscription/'
      preLoaderRoute: typeof AuthenticatedSellerSubscriptionIndexRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/subscription/payment': {
      id: '/_authenticated/seller/subscription/payment'
      path: '/subscription/payment'
      fullPath: '/seller/subscription/payment'
      preLoaderRoute: typeof AuthenticatedSellerSubscriptionPaymentRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminDisputesRoute: typeof AuthenticatedAdminDisputesRoute
  AuthenticatedAdminListingsRoute: typeof AuthenticatedAdminListingsRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSubscriptionsRoute: typeof AuthenticatedAdminSubscriptionsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
  AuthenticatedAdminDisputesRoute: AuthenticatedAdminDisputesRoute,
  AuthenticatedAdminListingsRoute: AuthenticatedAdminListingsRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminSubscriptionsRoute: AuthenticatedAdminSubscriptionsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedSellerRouteChildren {
  AuthenticatedSellerAdsRoute: typeof AuthenticatedSellerAdsRoute
  AuthenticatedSellerAnalyticsRoute: typeof AuthenticatedSellerAnalyticsRoute
  AuthenticatedSellerBoostsRoute: typeof AuthenticatedSellerBoostsRoute
  AuthenticatedSellerCouponsRoute: typeof AuthenticatedSellerCouponsRoute
  AuthenticatedSellerDeliveryRoute: typeof AuthenticatedSellerDeliveryRoute
  AuthenticatedSellerDisputesRoute: typeof AuthenticatedSellerDisputesRoute
  AuthenticatedSellerEarningsRoute: typeof AuthenticatedSellerEarningsRoute
  AuthenticatedSellerListingsRoute: typeof AuthenticatedSellerListingsRoute
  AuthenticatedSellerMessagesRoute: typeof AuthenticatedSellerMessagesRoute
  AuthenticatedSellerNotificationsRoute: typeof AuthenticatedSellerNotificationsRoute
  AuthenticatedSellerOrdersRoute: typeof AuthenticatedSellerOrdersRoute
  AuthenticatedSellerReviewsRoute: typeof AuthenticatedSellerReviewsRoute
  AuthenticatedSellerSecurityRoute: typeof AuthenticatedSellerSecurityRoute
  AuthenticatedSellerSettingsRoute: typeof AuthenticatedSellerSettingsRoute
  AuthenticatedSellerStoreRoute: typeof AuthenticatedSellerStoreRoute
  AuthenticatedSellerSupportRoute: typeof AuthenticatedSellerSupportRoute
  AuthenticatedSellerTransactionsRoute: typeof AuthenticatedSellerTransactionsRoute
  AuthenticatedSellerVerificationRoute: typeof AuthenticatedSellerVerificationRoute
  AuthenticatedSellerWalletRoute: typeof AuthenticatedSellerWalletRoute
  AuthenticatedSellerWithdrawalsRoute: typeof AuthenticatedSellerWithdrawalsRoute
  AuthenticatedSellerIndexRoute: typeof AuthenticatedSellerIndexRoute
  AuthenticatedSellerSubscriptionPaymentRoute: typeof AuthenticatedSellerSubscriptionPaymentRoute
  AuthenticatedSellerSubscriptionIndexRoute: typeof AuthenticatedSellerSubscriptionIndexRoute
}

const AuthenticatedSellerRouteChildren: AuthenticatedSellerRouteChildren = {
  AuthenticatedSellerAdsRoute: AuthenticatedSellerAdsRoute,
  AuthenticatedSellerAnalyticsRoute: AuthenticatedSellerAnalyticsRoute,
  AuthenticatedSellerBoostsRoute: AuthenticatedSellerBoostsRoute,
  AuthenticatedSellerCouponsRoute: AuthenticatedSellerCouponsRoute,
  AuthenticatedSellerDeliveryRoute: AuthenticatedSellerDeliveryRoute,
  AuthenticatedSellerDisputesRoute: AuthenticatedSellerDisputesRoute,
  AuthenticatedSellerEarningsRoute: AuthenticatedSellerEarningsRoute,
  AuthenticatedSellerListingsRoute: AuthenticatedSellerListingsRoute,
  AuthenticatedSellerMessagesRoute: AuthenticatedSellerMessagesRoute,
  AuthenticatedSellerNotificationsRoute: AuthenticatedSellerNotificationsRoute,
  AuthenticatedSellerOrdersRoute: AuthenticatedSellerOrdersRoute,
  AuthenticatedSellerReviewsRoute: AuthenticatedSellerReviewsRoute,
  AuthenticatedSellerSecurityRoute: AuthenticatedSellerSecurityRoute,
  AuthenticatedSellerSettingsRoute: AuthenticatedSellerSettingsRoute,
  AuthenticatedSellerStoreRoute: AuthenticatedSellerStoreRoute,
  AuthenticatedSellerSupportRoute: AuthenticatedSellerSupportRoute,
  AuthenticatedSellerTransactionsRoute: AuthenticatedSellerTransactionsRoute,
  AuthenticatedSellerVerificationRoute: AuthenticatedSellerVerificationRoute,
  AuthenticatedSellerWalletRoute: AuthenticatedSellerWalletRoute,
  AuthenticatedSellerWithdrawalsRoute: AuthenticatedSellerWithdrawalsRoute,
  AuthenticatedSellerIndexRoute: AuthenticatedSellerIndexRoute,
  AuthenticatedSellerSubscriptionPaymentRoute:
    AuthenticatedSellerSubscriptionPaymentRoute,
  AuthenticatedSellerSubscriptionIndexRoute:
    AuthenticatedSellerSubscriptionIndexRoute,
}

const AuthenticatedSellerRouteWithChildren =
  AuthenticatedSellerRoute._addFileChildren(AuthenticatedSellerRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedSellerRoute: typeof AuthenticatedSellerRouteWithChildren
  AuthenticatedCheckoutPaymentRoute: typeof AuthenticatedCheckoutPaymentRoute
  AuthenticatedCheckoutVerifyPaymentRoute: typeof AuthenticatedCheckoutVerifyPaymentRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedSellerRoute: AuthenticatedSellerRouteWithChildren,
  AuthenticatedCheckoutPaymentRoute: AuthenticatedCheckoutPaymentRoute,
  AuthenticatedCheckoutVerifyPaymentRoute:
    AuthenticatedCheckoutVerifyPaymentRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  BlogRoute: BlogRoute,
  CareersRoute: CareersRoute,
  CategoriesRoute: CategoriesRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SellerPanelRoute: SellerPanelRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthVerifiedRoute: AuthVerifiedRoute,
  CategorySlugRoute: CategorySlugRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
