/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TeamLoginRouteImport } from './routes/team-login'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SellerPanelRouteImport } from './routes/seller-panel'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PagesRouteImport } from './routes/pages'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as GameBuddiesRouteImport } from './routes/game-buddies'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoachingRouteImport } from './routes/coaching'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BecomeGameBuddyRouteImport } from './routes/become-game-buddy'
import { Route as BecomeCoachRouteImport } from './routes/become-coach'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as VerifyInvoiceNumberRouteImport } from './routes/verify.$invoiceNumber'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as GameBuddiesIdRouteImport } from './routes/game-buddies.$id'
import { Route as CoachingIdRouteImport } from './routes/coaching.$id'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as AuthVerifiedRouteImport } from './routes/auth.verified'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AccountVerifyPhoneRouteImport } from './routes/account.verify-phone'
import { Route as ServerTrackDurationRouteImport } from './routes/_server.trackDuration'
import { Route as AuthenticatedSuspendedRouteImport } from './routes/_authenticated/suspended'
import { Route as AuthenticatedSellerRouteImport } from './routes/_authenticated/seller'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedBannedRouteImport } from './routes/_authenticated/banned'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedSellerIndexRouteImport } from './routes/_authenticated/seller.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedSellerWithdrawalsRouteImport } from './routes/_authenticated/seller.withdrawals'
import { Route as AuthenticatedSellerWalletRouteImport } from './routes/_authenticated/seller.wallet'
import { Route as AuthenticatedSellerVerificationRouteImport } from './routes/_authenticated/seller.verification'
import { Route as AuthenticatedSellerTransactionsRouteImport } from './routes/_authenticated/seller.transactions'
import { Route as AuthenticatedSellerSupportRouteImport } from './routes/_authenticated/seller.support'
import { Route as AuthenticatedSellerStoreRouteImport } from './routes/_authenticated/seller.store'
import { Route as AuthenticatedSellerSettingsRouteImport } from './routes/_authenticated/seller.settings'
import { Route as AuthenticatedSellerSecurityRouteImport } from './routes/_authenticated/seller.security'
import { Route as AuthenticatedSellerReviewsRouteImport } from './routes/_authenticated/seller.reviews'
import { Route as AuthenticatedSellerOrdersRouteImport } from './routes/_authenticated/seller.orders'
import { Route as AuthenticatedSellerNotificationsRouteImport } from './routes/_authenticated/seller.notifications'
import { Route as AuthenticatedSellerMessagesRouteImport } from './routes/_authenticated/seller.messages'
import { Route as AuthenticatedSellerListingsRouteImport } from './routes/_authenticated/seller.listings'
import { Route as AuthenticatedSellerEarningsRouteImport } from './routes/_authenticated/seller.earnings'
import { Route as AuthenticatedSellerDisputesRouteImport } from './routes/_authenticated/seller.disputes'
import { Route as AuthenticatedSellerDeliveryRouteImport } from './routes/_authenticated/seller.delivery'
import { Route as AuthenticatedSellerCouponsRouteImport } from './routes/_authenticated/seller.coupons'
import { Route as AuthenticatedSellerBoostsRouteImport } from './routes/_authenticated/seller.boosts'
import { Route as AuthenticatedSellerAnalyticsRouteImport } from './routes/_authenticated/seller.analytics'
import { Route as AuthenticatedSellerAdsRouteImport } from './routes/_authenticated/seller.ads'
import { Route as AuthenticatedCheckoutVerifyPaymentRouteImport } from './routes/_authenticated/checkout.verify-payment'
import { Route as AuthenticatedCheckoutPaymentRouteImport } from './routes/_authenticated/checkout.payment'
import { Route as AuthenticatedAdminWithdrawalsRouteImport } from './routes/_authenticated/admin.withdrawals'
import { Route as AuthenticatedAdminVerificationsRouteImport } from './routes/_authenticated/admin.verifications'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminTicketsRouteImport } from './routes/_authenticated/admin.tickets'
import { Route as AuthenticatedAdminTasksRouteImport } from './routes/_authenticated/admin.tasks'
import { Route as AuthenticatedAdminSubscriptionsRouteImport } from './routes/_authenticated/admin.subscriptions'
import { Route as AuthenticatedAdminStaffRouteImport } from './routes/_authenticated/admin.staff'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminSeoRouteImport } from './routes/_authenticated/admin.seo'
import { Route as AuthenticatedAdminSecurityLogsRouteImport } from './routes/_authenticated/admin.security-logs'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin.payments'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin.orders'
import { Route as AuthenticatedAdminNewsletterRouteImport } from './routes/_authenticated/admin.newsletter'
import { Route as AuthenticatedAdminListingsRouteImport } from './routes/_authenticated/admin.listings'
import { Route as AuthenticatedAdminInvoicesRouteImport } from './routes/_authenticated/admin.invoices'
import { Route as AuthenticatedAdminInvoiceTemplatesRouteImport } from './routes/_authenticated/admin.invoice-templates'
import { Route as AuthenticatedAdminFinancesRouteImport } from './routes/_authenticated/admin.finances'
import { Route as AuthenticatedAdminEarningsRouteImport } from './routes/_authenticated/admin.earnings'
import { Route as AuthenticatedAdminDisputesRouteImport } from './routes/_authenticated/admin.disputes'
import { Route as AuthenticatedAdminCommunicationRouteImport } from './routes/_authenticated/admin.communication'
import { Route as AuthenticatedAdminChatsRouteImport } from './routes/_authenticated/admin.chats'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin.categories'
import { Route as AuthenticatedAdminBoostsRouteImport } from './routes/_authenticated/admin.boosts'
import { Route as AuthenticatedAdminAuditLogsRouteImport } from './routes/_authenticated/admin.audit-logs'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedSellerSubscriptionIndexRouteImport } from './routes/_authenticated/seller.subscription.index'
import { Route as AuthenticatedSellerSubscriptionPaymentRouteImport } from './routes/_authenticated/seller.subscription.payment'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamLoginRoute = TeamLoginRouteImport.update({
  id: '/team-login',
  path: '/team-login',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerPanelRoute = SellerPanelRouteImport.update({
  id: '/seller-panel',
  path: '/seller-panel',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesRoute = PagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const GameBuddiesRoute = GameBuddiesRouteImport.update({
  id: '/game-buddies',
  path: '/game-buddies',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachingRoute = CoachingRouteImport.update({
  id: '/coaching',
  path: '/coaching',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeGameBuddyRoute = BecomeGameBuddyRouteImport.update({
  id: '/become-game-buddy',
  path: '/become-game-buddy',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeCoachRoute = BecomeCoachRouteImport.update({
  id: '/become-coach',
  path: '/become-coach',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyInvoiceNumberRoute = VerifyInvoiceNumberRouteImport.update({
  id: '/verify/$invoiceNumber',
  path: '/verify/$invoiceNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GameBuddiesIdRoute = GameBuddiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GameBuddiesRoute,
} as any)
const CoachingIdRoute = CoachingIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CoachingRoute,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifiedRoute = AuthVerifiedRouteImport.update({
  id: '/auth/verified',
  path: '/auth/verified',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountVerifyPhoneRoute = AccountVerifyPhoneRouteImport.update({
  id: '/account/verify-phone',
  path: '/account/verify-phone',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerTrackDurationRoute = ServerTrackDurationRouteImport.update({
  id: '/_server/trackDuration',
  path: '/trackDuration',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSuspendedRoute = AuthenticatedSuspendedRouteImport.update({
  id: '/suspended',
  path: '/suspended',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSellerRoute = AuthenticatedSellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBannedRoute = AuthenticatedBannedRouteImport.update({
  id: '/banned',
  path: '/banned',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSellerIndexRoute =
  AuthenticatedSellerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedSellerWithdrawalsRoute =
  AuthenticatedSellerWithdrawalsRouteImport.update({
    id: '/withdrawals',
    path: '/withdrawals',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerWalletRoute =
  AuthenticatedSellerWalletRouteImport.update({
    id: '/wallet',
    path: '/wallet',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerVerificationRoute =
  AuthenticatedSellerVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerTransactionsRoute =
  AuthenticatedSellerTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerSupportRoute =
  AuthenticatedSellerSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerStoreRoute =
  AuthenticatedSellerStoreRouteImport.update({
    id: '/store',
    path: '/store',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerSettingsRoute =
  AuthenticatedSellerSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerSecurityRoute =
  AuthenticatedSellerSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerReviewsRoute =
  AuthenticatedSellerReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerOrdersRoute =
  AuthenticatedSellerOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerNotificationsRoute =
  AuthenticatedSellerNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerMessagesRoute =
  AuthenticatedSellerMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerListingsRoute =
  AuthenticatedSellerListingsRouteImport.update({
    id: '/listings',
    path: '/listings',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerEarningsRoute =
  AuthenticatedSellerEarningsRouteImport.update({
    id: '/earnings',
    path: '/earnings',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerDisputesRoute =
  AuthenticatedSellerDisputesRouteImport.update({
    id: '/disputes',
    path: '/disputes',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerDeliveryRoute =
  AuthenticatedSellerDeliveryRouteImport.update({
    id: '/delivery',
    path: '/delivery',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerCouponsRoute =
  AuthenticatedSellerCouponsRouteImport.update({
    id: '/coupons',
    path: '/coupons',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerBoostsRoute =
  AuthenticatedSellerBoostsRouteImport.update({
    id: '/boosts',
    path: '/boosts',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerAnalyticsRoute =
  AuthenticatedSellerAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerAdsRoute = AuthenticatedSellerAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AuthenticatedSellerRoute,
} as any)
const AuthenticatedCheckoutVerifyPaymentRoute =
  AuthenticatedCheckoutVerifyPaymentRouteImport.update({
    id: '/checkout/verify-payment',
    path: '/checkout/verify-payment',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCheckoutPaymentRoute =
  AuthenticatedCheckoutPaymentRouteImport.update({
    id: '/checkout/payment',
    path: '/checkout/payment',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminWithdrawalsRoute =
  AuthenticatedAdminWithdrawalsRouteImport.update({
    id: '/withdrawals',
    path: '/withdrawals',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminVerificationsRoute =
  AuthenticatedAdminVerificationsRouteImport.update({
    id: '/verifications',
    path: '/verifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTicketsRoute =
  AuthenticatedAdminTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTasksRoute = AuthenticatedAdminTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSubscriptionsRoute =
  AuthenticatedAdminSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStaffRoute = AuthenticatedAdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSeoRoute = AuthenticatedAdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSecurityLogsRoute =
  AuthenticatedAdminSecurityLogsRouteImport.update({
    id: '/security-logs',
    path: '/security-logs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNewsletterRoute =
  AuthenticatedAdminNewsletterRouteImport.update({
    id: '/newsletter',
    path: '/newsletter',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminListingsRoute =
  AuthenticatedAdminListingsRouteImport.update({
    id: '/listings',
    path: '/listings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInvoicesRoute =
  AuthenticatedAdminInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInvoiceTemplatesRoute =
  AuthenticatedAdminInvoiceTemplatesRouteImport.update({
    id: '/invoice-templates',
    path: '/invoice-templates',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFinancesRoute =
  AuthenticatedAdminFinancesRouteImport.update({
    id: '/finances',
    path: '/finances',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEarningsRoute =
  AuthenticatedAdminEarningsRouteImport.update({
    id: '/earnings',
    path: '/earnings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDisputesRoute =
  AuthenticatedAdminDisputesRouteImport.update({
    id: '/disputes',
    path: '/disputes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCommunicationRoute =
  AuthenticatedAdminCommunicationRouteImport.update({
    id: '/communication',
    path: '/communication',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminChatsRoute = AuthenticatedAdminChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBoostsRoute =
  AuthenticatedAdminBoostsRouteImport.update({
    id: '/boosts',
    path: '/boosts',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditLogsRoute =
  AuthenticatedAdminAuditLogsRouteImport.update({
    id: '/audit-logs',
    path: '/audit-logs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedSellerSubscriptionIndexRoute =
  AuthenticatedSellerSubscriptionIndexRouteImport.update({
    id: '/subscription/',
    path: '/subscription/',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerSubscriptionPaymentRoute =
  AuthenticatedSellerSubscriptionPaymentRouteImport.update({
    id: '/subscription/payment',
    path: '/subscription/payment',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-coach': typeof BecomeCoachRoute
  '/become-game-buddy': typeof BecomeGameBuddyRoute
  '/blog': typeof BlogRoute
  '/browse': typeof BrowseRoute
  '/careers': typeof CareersRoute
  '/categories': typeof CategoriesRoute
  '/coaching': typeof CoachingRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/game-buddies': typeof GameBuddiesRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/pages': typeof PagesRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/seller-panel': typeof SellerPanelRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team-login': typeof TeamLoginRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/banned': typeof AuthenticatedBannedRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/seller': typeof AuthenticatedSellerRouteWithChildren
  '/suspended': typeof AuthenticatedSuspendedRoute
  '/trackDuration': typeof ServerTrackDurationRoute
  '/account/verify-phone': typeof AccountVerifyPhoneRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/verified': typeof AuthVerifiedRoute
  '/category/$slug': typeof CategorySlugRoute
  '/coaching/$id': typeof CoachingIdRoute
  '/game-buddies/$id': typeof GameBuddiesIdRoute
  '/product/$id': typeof ProductIdRoute
  '/verify/$invoiceNumber': typeof VerifyInvoiceNumberRoute
  '/account/': typeof AccountIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/admin/boosts': typeof AuthenticatedAdminBoostsRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/chats': typeof AuthenticatedAdminChatsRoute
  '/admin/communication': typeof AuthenticatedAdminCommunicationRoute
  '/admin/disputes': typeof AuthenticatedAdminDisputesRoute
  '/admin/earnings': typeof AuthenticatedAdminEarningsRoute
  '/admin/finances': typeof AuthenticatedAdminFinancesRoute
  '/admin/invoice-templates': typeof AuthenticatedAdminInvoiceTemplatesRoute
  '/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/admin/listings': typeof AuthenticatedAdminListingsRoute
  '/admin/newsletter': typeof AuthenticatedAdminNewsletterRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/security-logs': typeof AuthenticatedAdminSecurityLogsRoute
  '/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/admin/tasks': typeof AuthenticatedAdminTasksRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/verifications': typeof AuthenticatedAdminVerificationsRoute
  '/admin/withdrawals': typeof AuthenticatedAdminWithdrawalsRoute
  '/checkout/payment': typeof AuthenticatedCheckoutPaymentRoute
  '/checkout/verify-payment': typeof AuthenticatedCheckoutVerifyPaymentRoute
  '/seller/ads': typeof AuthenticatedSellerAdsRoute
  '/seller/analytics': typeof AuthenticatedSellerAnalyticsRoute
  '/seller/boosts': typeof AuthenticatedSellerBoostsRoute
  '/seller/coupons': typeof AuthenticatedSellerCouponsRoute
  '/seller/delivery': typeof AuthenticatedSellerDeliveryRoute
  '/seller/disputes': typeof AuthenticatedSellerDisputesRoute
  '/seller/earnings': typeof AuthenticatedSellerEarningsRoute
  '/seller/listings': typeof AuthenticatedSellerListingsRoute
  '/seller/messages': typeof AuthenticatedSellerMessagesRoute
  '/seller/notifications': typeof AuthenticatedSellerNotificationsRoute
  '/seller/orders': typeof AuthenticatedSellerOrdersRoute
  '/seller/reviews': typeof AuthenticatedSellerReviewsRoute
  '/seller/security': typeof AuthenticatedSellerSecurityRoute
  '/seller/settings': typeof AuthenticatedSellerSettingsRoute
  '/seller/store': typeof AuthenticatedSellerStoreRoute
  '/seller/support': typeof AuthenticatedSellerSupportRoute
  '/seller/transactions': typeof AuthenticatedSellerTransactionsRoute
  '/seller/verification': typeof AuthenticatedSellerVerificationRoute
  '/seller/wallet': typeof AuthenticatedSellerWalletRoute
  '/seller/withdrawals': typeof AuthenticatedSellerWithdrawalsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/seller/': typeof AuthenticatedSellerIndexRoute
  '/seller/subscription/payment': typeof AuthenticatedSellerSubscriptionPaymentRoute
  '/seller/subscription/': typeof AuthenticatedSellerSubscriptionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-coach': typeof BecomeCoachRoute
  '/become-game-buddy': typeof BecomeGameBuddyRoute
  '/blog': typeof BlogRoute
  '/browse': typeof BrowseRoute
  '/careers': typeof CareersRoute
  '/categories': typeof CategoriesRoute
  '/coaching': typeof CoachingRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/game-buddies': typeof GameBuddiesRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/pages': typeof PagesRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/seller-panel': typeof SellerPanelRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team-login': typeof TeamLoginRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/banned': typeof AuthenticatedBannedRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/suspended': typeof AuthenticatedSuspendedRoute
  '/trackDuration': typeof ServerTrackDurationRoute
  '/account/verify-phone': typeof AccountVerifyPhoneRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/verified': typeof AuthVerifiedRoute
  '/category/$slug': typeof CategorySlugRoute
  '/coaching/$id': typeof CoachingIdRoute
  '/game-buddies/$id': typeof GameBuddiesIdRoute
  '/product/$id': typeof ProductIdRoute
  '/verify/$invoiceNumber': typeof VerifyInvoiceNumberRoute
  '/account': typeof AccountIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/admin/boosts': typeof AuthenticatedAdminBoostsRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/chats': typeof AuthenticatedAdminChatsRoute
  '/admin/communication': typeof AuthenticatedAdminCommunicationRoute
  '/admin/disputes': typeof AuthenticatedAdminDisputesRoute
  '/admin/earnings': typeof AuthenticatedAdminEarningsRoute
  '/admin/finances': typeof AuthenticatedAdminFinancesRoute
  '/admin/invoice-templates': typeof AuthenticatedAdminInvoiceTemplatesRoute
  '/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/admin/listings': typeof AuthenticatedAdminListingsRoute
  '/admin/newsletter': typeof AuthenticatedAdminNewsletterRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/security-logs': typeof AuthenticatedAdminSecurityLogsRoute
  '/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/admin/tasks': typeof AuthenticatedAdminTasksRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/verifications': typeof AuthenticatedAdminVerificationsRoute
  '/admin/withdrawals': typeof AuthenticatedAdminWithdrawalsRoute
  '/checkout/payment': typeof AuthenticatedCheckoutPaymentRoute
  '/checkout/verify-payment': typeof AuthenticatedCheckoutVerifyPaymentRoute
  '/seller/ads': typeof AuthenticatedSellerAdsRoute
  '/seller/analytics': typeof AuthenticatedSellerAnalyticsRoute
  '/seller/boosts': typeof AuthenticatedSellerBoostsRoute
  '/seller/coupons': typeof AuthenticatedSellerCouponsRoute
  '/seller/delivery': typeof AuthenticatedSellerDeliveryRoute
  '/seller/disputes': typeof AuthenticatedSellerDisputesRoute
  '/seller/earnings': typeof AuthenticatedSellerEarningsRoute
  '/seller/listings': typeof AuthenticatedSellerListingsRoute
  '/seller/messages': typeof AuthenticatedSellerMessagesRoute
  '/seller/notifications': typeof AuthenticatedSellerNotificationsRoute
  '/seller/orders': typeof AuthenticatedSellerOrdersRoute
  '/seller/reviews': typeof AuthenticatedSellerReviewsRoute
  '/seller/security': typeof AuthenticatedSellerSecurityRoute
  '/seller/settings': typeof AuthenticatedSellerSettingsRoute
  '/seller/store': typeof AuthenticatedSellerStoreRoute
  '/seller/support': typeof AuthenticatedSellerSupportRoute
  '/seller/transactions': typeof AuthenticatedSellerTransactionsRoute
  '/seller/verification': typeof AuthenticatedSellerVerificationRoute
  '/seller/wallet': typeof AuthenticatedSellerWalletRoute
  '/seller/withdrawals': typeof AuthenticatedSellerWithdrawalsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/seller': typeof AuthenticatedSellerIndexRoute
  '/seller/subscription/payment': typeof AuthenticatedSellerSubscriptionPaymentRoute
  '/seller/subscription': typeof AuthenticatedSellerSubscriptionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/become-coach': typeof BecomeCoachRoute
  '/become-game-buddy': typeof BecomeGameBuddyRoute
  '/blog': typeof BlogRoute
  '/browse': typeof BrowseRoute
  '/careers': typeof CareersRoute
  '/categories': typeof CategoriesRoute
  '/coaching': typeof CoachingRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/game-buddies': typeof GameBuddiesRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/pages': typeof PagesRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/seller-panel': typeof SellerPanelRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team-login': typeof TeamLoginRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/banned': typeof AuthenticatedBannedRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/seller': typeof AuthenticatedSellerRouteWithChildren
  '/_authenticated/suspended': typeof AuthenticatedSuspendedRoute
  '/_server/trackDuration': typeof ServerTrackDurationRoute
  '/account/verify-phone': typeof AccountVerifyPhoneRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/verified': typeof AuthVerifiedRoute
  '/category/$slug': typeof CategorySlugRoute
  '/coaching/$id': typeof CoachingIdRoute
  '/game-buddies/$id': typeof GameBuddiesIdRoute
  '/product/$id': typeof ProductIdRoute
  '/verify/$invoiceNumber': typeof VerifyInvoiceNumberRoute
  '/account/': typeof AccountIndexRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/_authenticated/admin/boosts': typeof AuthenticatedAdminBoostsRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/chats': typeof AuthenticatedAdminChatsRoute
  '/_authenticated/admin/communication': typeof AuthenticatedAdminCommunicationRoute
  '/_authenticated/admin/disputes': typeof AuthenticatedAdminDisputesRoute
  '/_authenticated/admin/earnings': typeof AuthenticatedAdminEarningsRoute
  '/_authenticated/admin/finances': typeof AuthenticatedAdminFinancesRoute
  '/_authenticated/admin/invoice-templates': typeof AuthenticatedAdminInvoiceTemplatesRoute
  '/_authenticated/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/_authenticated/admin/listings': typeof AuthenticatedAdminListingsRoute
  '/_authenticated/admin/newsletter': typeof AuthenticatedAdminNewsletterRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/security-logs': typeof AuthenticatedAdminSecurityLogsRoute
  '/_authenticated/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/_authenticated/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/_authenticated/admin/tasks': typeof AuthenticatedAdminTasksRoute
  '/_authenticated/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/verifications': typeof AuthenticatedAdminVerificationsRoute
  '/_authenticated/admin/withdrawals': typeof AuthenticatedAdminWithdrawalsRoute
  '/_authenticated/checkout/payment': typeof AuthenticatedCheckoutPaymentRoute
  '/_authenticated/checkout/verify-payment': typeof AuthenticatedCheckoutVerifyPaymentRoute
  '/_authenticated/seller/ads': typeof AuthenticatedSellerAdsRoute
  '/_authenticated/seller/analytics': typeof AuthenticatedSellerAnalyticsRoute
  '/_authenticated/seller/boosts': typeof AuthenticatedSellerBoostsRoute
  '/_authenticated/seller/coupons': typeof AuthenticatedSellerCouponsRoute
  '/_authenticated/seller/delivery': typeof AuthenticatedSellerDeliveryRoute
  '/_authenticated/seller/disputes': typeof AuthenticatedSellerDisputesRoute
  '/_authenticated/seller/earnings': typeof AuthenticatedSellerEarningsRoute
  '/_authenticated/seller/listings': typeof AuthenticatedSellerListingsRoute
  '/_authenticated/seller/messages': typeof AuthenticatedSellerMessagesRoute
  '/_authenticated/seller/notifications': typeof AuthenticatedSellerNotificationsRoute
  '/_authenticated/seller/orders': typeof AuthenticatedSellerOrdersRoute
  '/_authenticated/seller/reviews': typeof AuthenticatedSellerReviewsRoute
  '/_authenticated/seller/security': typeof AuthenticatedSellerSecurityRoute
  '/_authenticated/seller/settings': typeof AuthenticatedSellerSettingsRoute
  '/_authenticated/seller/store': typeof AuthenticatedSellerStoreRoute
  '/_authenticated/seller/support': typeof AuthenticatedSellerSupportRoute
  '/_authenticated/seller/transactions': typeof AuthenticatedSellerTransactionsRoute
  '/_authenticated/seller/verification': typeof AuthenticatedSellerVerificationRoute
  '/_authenticated/seller/wallet': typeof AuthenticatedSellerWalletRoute
  '/_authenticated/seller/withdrawals': typeof AuthenticatedSellerWithdrawalsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/seller/': typeof AuthenticatedSellerIndexRoute
  '/_authenticated/seller/subscription/payment': typeof AuthenticatedSellerSubscriptionPaymentRoute
  '/_authenticated/seller/subscription/': typeof AuthenticatedSellerSubscriptionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/become-coach'
    | '/become-game-buddy'
    | '/blog'
    | '/browse'
    | '/careers'
    | '/categories'
    | '/coaching'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/game-buddies'
    | '/how-it-works'
    | '/login'
    | '/orders'
    | '/pages'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/search'
    | '/seller-panel'
    | '/signup'
    | '/sitemap.xml'
    | '/team-login'
    | '/terms'
    | '/verify-email'
    | '/admin'
    | '/banned'
    | '/messages'
    | '/seller'
    | '/suspended'
    | '/trackDuration'
    | '/account/verify-phone'
    | '/auth/callback'
    | '/auth/verified'
    | '/category/$slug'
    | '/coaching/$id'
    | '/game-buddies/$id'
    | '/product/$id'
    | '/verify/$invoiceNumber'
    | '/account/'
    | '/admin/analytics'
    | '/admin/audit-logs'
    | '/admin/boosts'
    | '/admin/categories'
    | '/admin/chats'
    | '/admin/communication'
    | '/admin/disputes'
    | '/admin/earnings'
    | '/admin/finances'
    | '/admin/invoice-templates'
    | '/admin/invoices'
    | '/admin/listings'
    | '/admin/newsletter'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/security-logs'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/subscriptions'
    | '/admin/tasks'
    | '/admin/tickets'
    | '/admin/users'
    | '/admin/verifications'
    | '/admin/withdrawals'
    | '/checkout/payment'
    | '/checkout/verify-payment'
    | '/seller/ads'
    | '/seller/analytics'
    | '/seller/boosts'
    | '/seller/coupons'
    | '/seller/delivery'
    | '/seller/disputes'
    | '/seller/earnings'
    | '/seller/listings'
    | '/seller/messages'
    | '/seller/notifications'
    | '/seller/orders'
    | '/seller/reviews'
    | '/seller/security'
    | '/seller/settings'
    | '/seller/store'
    | '/seller/support'
    | '/seller/transactions'
    | '/seller/verification'
    | '/seller/wallet'
    | '/seller/withdrawals'
    | '/admin/'
    | '/seller/'
    | '/seller/subscription/payment'
    | '/seller/subscription/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/become-coach'
    | '/become-game-buddy'
    | '/blog'
    | '/browse'
    | '/careers'
    | '/categories'
    | '/coaching'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/game-buddies'
    | '/how-it-works'
    | '/login'
    | '/orders'
    | '/pages'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/search'
    | '/seller-panel'
    | '/signup'
    | '/sitemap.xml'
    | '/team-login'
    | '/terms'
    | '/verify-email'
    | '/banned'
    | '/messages'
    | '/suspended'
    | '/trackDuration'
    | '/account/verify-phone'
    | '/auth/callback'
    | '/auth/verified'
    | '/category/$slug'
    | '/coaching/$id'
    | '/game-buddies/$id'
    | '/product/$id'
    | '/verify/$invoiceNumber'
    | '/account'
    | '/admin/analytics'
    | '/admin/audit-logs'
    | '/admin/boosts'
    | '/admin/categories'
    | '/admin/chats'
    | '/admin/communication'
    | '/admin/disputes'
    | '/admin/earnings'
    | '/admin/finances'
    | '/admin/invoice-templates'
    | '/admin/invoices'
    | '/admin/listings'
    | '/admin/newsletter'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/security-logs'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/subscriptions'
    | '/admin/tasks'
    | '/admin/tickets'
    | '/admin/users'
    | '/admin/verifications'
    | '/admin/withdrawals'
    | '/checkout/payment'
    | '/checkout/verify-payment'
    | '/seller/ads'
    | '/seller/analytics'
    | '/seller/boosts'
    | '/seller/coupons'
    | '/seller/delivery'
    | '/seller/disputes'
    | '/seller/earnings'
    | '/seller/listings'
    | '/seller/messages'
    | '/seller/notifications'
    | '/seller/orders'
    | '/seller/reviews'
    | '/seller/security'
    | '/seller/settings'
    | '/seller/store'
    | '/seller/support'
    | '/seller/transactions'
    | '/seller/verification'
    | '/seller/wallet'
    | '/seller/withdrawals'
    | '/admin'
    | '/seller'
    | '/seller/subscription/payment'
    | '/seller/subscription'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/become-coach'
    | '/become-game-buddy'
    | '/blog'
    | '/browse'
    | '/careers'
    | '/categories'
    | '/coaching'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/game-buddies'
    | '/how-it-works'
    | '/login'
    | '/orders'
    | '/pages'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/search'
    | '/seller-panel'
    | '/signup'
    | '/sitemap.xml'
    | '/team-login'
    | '/terms'
    | '/verify-email'
    | '/_authenticated/admin'
    | '/_authenticated/banned'
    | '/_authenticated/messages'
    | '/_authenticated/seller'
    | '/_authenticated/suspended'
    | '/_server/trackDuration'
    | '/account/verify-phone'
    | '/auth/callback'
    | '/auth/verified'
    | '/category/$slug'
    | '/coaching/$id'
    | '/game-buddies/$id'
    | '/product/$id'
    | '/verify/$invoiceNumber'
    | '/account/'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/audit-logs'
    | '/_authenticated/admin/boosts'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/chats'
    | '/_authenticated/admin/communication'
    | '/_authenticated/admin/disputes'
    | '/_authenticated/admin/earnings'
    | '/_authenticated/admin/finances'
    | '/_authenticated/admin/invoice-templates'
    | '/_authenticated/admin/invoices'
    | '/_authenticated/admin/listings'
    | '/_authenticated/admin/newsletter'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/security-logs'
    | '/_authenticated/admin/seo'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/staff'
    | '/_authenticated/admin/subscriptions'
    | '/_authenticated/admin/tasks'
    | '/_authenticated/admin/tickets'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/verifications'
    | '/_authenticated/admin/withdrawals'
    | '/_authenticated/checkout/payment'
    | '/_authenticated/checkout/verify-payment'
    | '/_authenticated/seller/ads'
    | '/_authenticated/seller/analytics'
    | '/_authenticated/seller/boosts'
    | '/_authenticated/seller/coupons'
    | '/_authenticated/seller/delivery'
    | '/_authenticated/seller/disputes'
    | '/_authenticated/seller/earnings'
    | '/_authenticated/seller/listings'
    | '/_authenticated/seller/messages'
    | '/_authenticated/seller/notifications'
    | '/_authenticated/seller/orders'
    | '/_authenticated/seller/reviews'
    | '/_authenticated/seller/security'
    | '/_authenticated/seller/settings'
    | '/_authenticated/seller/store'
    | '/_authenticated/seller/support'
    | '/_authenticated/seller/transactions'
    | '/_authenticated/seller/verification'
    | '/_authenticated/seller/wallet'
    | '/_authenticated/seller/withdrawals'
    | '/_authenticated/admin/'
    | '/_authenticated/seller/'
    | '/_authenticated/seller/subscription/payment'
    | '/_authenticated/seller/subscription/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  BecomeCoachRoute: typeof BecomeCoachRoute
  BecomeGameBuddyRoute: typeof BecomeGameBuddyRoute
  BlogRoute: typeof BlogRoute
  BrowseRoute: typeof BrowseRoute
  CareersRoute: typeof CareersRoute
  CategoriesRoute: typeof CategoriesRoute
  CoachingRoute: typeof CoachingRouteWithChildren
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GameBuddiesRoute: typeof GameBuddiesRouteWithChildren
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRoute
  PagesRoute: typeof PagesRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SellerPanelRoute: typeof SellerPanelRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeamLoginRoute: typeof TeamLoginRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ServerTrackDurationRoute: typeof ServerTrackDurationRoute
  AccountVerifyPhoneRoute: typeof AccountVerifyPhoneRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthVerifiedRoute: typeof AuthVerifiedRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ProductIdRoute: typeof ProductIdRoute
  VerifyInvoiceNumberRoute: typeof VerifyInvoiceNumberRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-login': {
      id: '/team-login'
      path: '/team-login'
      fullPath: '/team-login'
      preLoaderRoute: typeof TeamLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller-panel': {
      id: '/seller-panel'
      path: '/seller-panel'
      fullPath: '/seller-panel'
      preLoaderRoute: typeof SellerPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages': {
      id: '/pages'
      path: '/pages'
      fullPath: '/pages'
      preLoaderRoute: typeof PagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game-buddies': {
      id: '/game-buddies'
      path: '/game-buddies'
      fullPath: '/game-buddies'
      preLoaderRoute: typeof GameBuddiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaching': {
      id: '/coaching'
      path: '/coaching'
      fullPath: '/coaching'
      preLoaderRoute: typeof CoachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-game-buddy': {
      id: '/become-game-buddy'
      path: '/become-game-buddy'
      fullPath: '/become-game-buddy'
      preLoaderRoute: typeof BecomeGameBuddyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-coach': {
      id: '/become-coach'
      path: '/become-coach'
      fullPath: '/become-coach'
      preLoaderRoute: typeof BecomeCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$invoiceNumber': {
      id: '/verify/$invoiceNumber'
      path: '/verify/$invoiceNumber'
      fullPath: '/verify/$invoiceNumber'
      preLoaderRoute: typeof VerifyInvoiceNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game-buddies/$id': {
      id: '/game-buddies/$id'
      path: '/$id'
      fullPath: '/game-buddies/$id'
      preLoaderRoute: typeof GameBuddiesIdRouteImport
      parentRoute: typeof GameBuddiesRoute
    }
    '/coaching/$id': {
      id: '/coaching/$id'
      path: '/$id'
      fullPath: '/coaching/$id'
      preLoaderRoute: typeof CoachingIdRouteImport
      parentRoute: typeof CoachingRoute
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verified': {
      id: '/auth/verified'
      path: '/auth/verified'
      fullPath: '/auth/verified'
      preLoaderRoute: typeof AuthVerifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/verify-phone': {
      id: '/account/verify-phone'
      path: '/account/verify-phone'
      fullPath: '/account/verify-phone'
      preLoaderRoute: typeof AccountVerifyPhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_server/trackDuration': {
      id: '/_server/trackDuration'
      path: '/trackDuration'
      fullPath: '/trackDuration'
      preLoaderRoute: typeof ServerTrackDurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/suspended': {
      id: '/_authenticated/suspended'
      path: '/suspended'
      fullPath: '/suspended'
      preLoaderRoute: typeof AuthenticatedSuspendedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/seller': {
      id: '/_authenticated/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof AuthenticatedSellerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/banned': {
      id: '/_authenticated/banned'
      path: '/banned'
      fullPath: '/banned'
      preLoaderRoute: typeof AuthenticatedBannedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/seller/': {
      id: '/_authenticated/seller/'
      path: '/'
      fullPath: '/seller/'
      preLoaderRoute: typeof AuthenticatedSellerIndexRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/seller/withdrawals': {
      id: '/_authenticated/seller/withdrawals'
      path: '/withdrawals'
      fullPath: '/seller/withdrawals'
      preLoaderRoute: typeof AuthenticatedSellerWithdrawalsRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/wallet': {
      id: '/_authenticated/seller/wallet'
      path: '/wallet'
      fullPath: '/seller/wallet'
      preLoaderRoute: typeof AuthenticatedSellerWalletRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/verification': {
      id: '/_authenticated/seller/verification'
      path: '/verification'
      fullPath: '/seller/verification'
      preLoaderRoute: typeof AuthenticatedSellerVerificationRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/transactions': {
      id: '/_authenticated/seller/transactions'
      path: '/transactions'
      fullPath: '/seller/transactions'
      preLoaderRoute: typeof AuthenticatedSellerTransactionsRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/support': {
      id: '/_authenticated/seller/support'
      path: '/support'
      fullPath: '/seller/support'
      preLoaderRoute: typeof AuthenticatedSellerSupportRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/store': {
      id: '/_authenticated/seller/store'
      path: '/store'
      fullPath: '/seller/store'
      preLoaderRoute: typeof AuthenticatedSellerStoreRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/settings': {
      id: '/_authenticated/seller/settings'
      path: '/settings'
      fullPath: '/seller/settings'
      preLoaderRoute: typeof AuthenticatedSellerSettingsRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/security': {
      id: '/_authenticated/seller/security'
      path: '/security'
      fullPath: '/seller/security'
      preLoaderRoute: typeof AuthenticatedSellerSecurityRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/reviews': {
      id: '/_authenticated/seller/reviews'
      path: '/reviews'
      fullPath: '/seller/reviews'
      preLoaderRoute: typeof AuthenticatedSellerReviewsRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/orders': {
      id: '/_authenticated/seller/orders'
      path: '/orders'
      fullPath: '/seller/orders'
      preLoaderRoute: typeof AuthenticatedSellerOrdersRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/notifications': {
      id: '/_authenticated/seller/notifications'
      path: '/notifications'
      fullPath: '/seller/notifications'
      preLoaderRoute: typeof AuthenticatedSellerNotificationsRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/messages': {
      id: '/_authenticated/seller/messages'
      path: '/messages'
      fullPath: '/seller/messages'
      preLoaderRoute: typeof AuthenticatedSellerMessagesRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/listings': {
      id: '/_authenticated/seller/listings'
      path: '/listings'
      fullPath: '/seller/listings'
      preLoaderRoute: typeof AuthenticatedSellerListingsRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/earnings': {
      id: '/_authenticated/seller/earnings'
      path: '/earnings'
      fullPath: '/seller/earnings'
      preLoaderRoute: typeof AuthenticatedSellerEarningsRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/disputes': {
      id: '/_authenticated/seller/disputes'
      path: '/disputes'
      fullPath: '/seller/disputes'
      preLoaderRoute: typeof AuthenticatedSellerDisputesRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/delivery': {
      id: '/_authenticated/seller/delivery'
      path: '/delivery'
      fullPath: '/seller/delivery'
      preLoaderRoute: typeof AuthenticatedSellerDeliveryRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/coupons': {
      id: '/_authenticated/seller/coupons'
      path: '/coupons'
      fullPath: '/seller/coupons'
      preLoaderRoute: typeof AuthenticatedSellerCouponsRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/boosts': {
      id: '/_authenticated/seller/boosts'
      path: '/boosts'
      fullPath: '/seller/boosts'
      preLoaderRoute: typeof AuthenticatedSellerBoostsRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/analytics': {
      id: '/_authenticated/seller/analytics'
      path: '/analytics'
      fullPath: '/seller/analytics'
      preLoaderRoute: typeof AuthenticatedSellerAnalyticsRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/ads': {
      id: '/_authenticated/seller/ads'
      path: '/ads'
      fullPath: '/seller/ads'
      preLoaderRoute: typeof AuthenticatedSellerAdsRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/checkout/verify-payment': {
      id: '/_authenticated/checkout/verify-payment'
      path: '/checkout/verify-payment'
      fullPath: '/checkout/verify-payment'
      preLoaderRoute: typeof AuthenticatedCheckoutVerifyPaymentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checkout/payment': {
      id: '/_authenticated/checkout/payment'
      path: '/checkout/payment'
      fullPath: '/checkout/payment'
      preLoaderRoute: typeof AuthenticatedCheckoutPaymentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/withdrawals': {
      id: '/_authenticated/admin/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AuthenticatedAdminWithdrawalsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/verifications': {
      id: '/_authenticated/admin/verifications'
      path: '/verifications'
      fullPath: '/admin/verifications'
      preLoaderRoute: typeof AuthenticatedAdminVerificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tickets': {
      id: '/_authenticated/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AuthenticatedAdminTicketsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tasks': {
      id: '/_authenticated/admin/tasks'
      path: '/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AuthenticatedAdminTasksRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/subscriptions': {
      id: '/_authenticated/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AuthenticatedAdminSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/staff': {
      id: '/_authenticated/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AuthenticatedAdminStaffRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/seo': {
      id: '/_authenticated/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AuthenticatedAdminSeoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/security-logs': {
      id: '/_authenticated/admin/security-logs'
      path: '/security-logs'
      fullPath: '/admin/security-logs'
      preLoaderRoute: typeof AuthenticatedAdminSecurityLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/newsletter': {
      id: '/_authenticated/admin/newsletter'
      path: '/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AuthenticatedAdminNewsletterRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/listings': {
      id: '/_authenticated/admin/listings'
      path: '/listings'
      fullPath: '/admin/listings'
      preLoaderRoute: typeof AuthenticatedAdminListingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/invoices': {
      id: '/_authenticated/admin/invoices'
      path: '/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AuthenticatedAdminInvoicesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/invoice-templates': {
      id: '/_authenticated/admin/invoice-templates'
      path: '/invoice-templates'
      fullPath: '/admin/invoice-templates'
      preLoaderRoute: typeof AuthenticatedAdminInvoiceTemplatesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/finances': {
      id: '/_authenticated/admin/finances'
      path: '/finances'
      fullPath: '/admin/finances'
      preLoaderRoute: typeof AuthenticatedAdminFinancesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/earnings': {
      id: '/_authenticated/admin/earnings'
      path: '/earnings'
      fullPath: '/admin/earnings'
      preLoaderRoute: typeof AuthenticatedAdminEarningsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/disputes': {
      id: '/_authenticated/admin/disputes'
      path: '/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AuthenticatedAdminDisputesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/communication': {
      id: '/_authenticated/admin/communication'
      path: '/communication'
      fullPath: '/admin/communication'
      preLoaderRoute: typeof AuthenticatedAdminCommunicationRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/chats': {
      id: '/_authenticated/admin/chats'
      path: '/chats'
      fullPath: '/admin/chats'
      preLoaderRoute: typeof AuthenticatedAdminChatsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/boosts': {
      id: '/_authenticated/admin/boosts'
      path: '/boosts'
      fullPath: '/admin/boosts'
      preLoaderRoute: typeof AuthenticatedAdminBoostsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit-logs': {
      id: '/_authenticated/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AuthenticatedAdminAuditLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/seller/subscription/': {
      id: '/_authenticated/seller/subscription/'
      path: '/subscription'
      fullPath: '/seller/subscription/'
      preLoaderRoute: typeof AuthenticatedSellerSubscriptionIndexRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/subscription/payment': {
      id: '/_authenticated/seller/subscription/payment'
      path: '/subscription/payment'
      fullPath: '/seller/subscription/payment'
      preLoaderRoute: typeof AuthenticatedSellerSubscriptionPaymentRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminAuditLogsRoute: typeof AuthenticatedAdminAuditLogsRoute
  AuthenticatedAdminBoostsRoute: typeof AuthenticatedAdminBoostsRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminChatsRoute: typeof AuthenticatedAdminChatsRoute
  AuthenticatedAdminCommunicationRoute: typeof AuthenticatedAdminCommunicationRoute
  AuthenticatedAdminDisputesRoute: typeof AuthenticatedAdminDisputesRoute
  AuthenticatedAdminEarningsRoute: typeof AuthenticatedAdminEarningsRoute
  AuthenticatedAdminFinancesRoute: typeof AuthenticatedAdminFinancesRoute
  AuthenticatedAdminInvoiceTemplatesRoute: typeof AuthenticatedAdminInvoiceTemplatesRoute
  AuthenticatedAdminInvoicesRoute: typeof AuthenticatedAdminInvoicesRoute
  AuthenticatedAdminListingsRoute: typeof AuthenticatedAdminListingsRoute
  AuthenticatedAdminNewsletterRoute: typeof AuthenticatedAdminNewsletterRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminSecurityLogsRoute: typeof AuthenticatedAdminSecurityLogsRoute
  AuthenticatedAdminSeoRoute: typeof AuthenticatedAdminSeoRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStaffRoute: typeof AuthenticatedAdminStaffRoute
  AuthenticatedAdminSubscriptionsRoute: typeof AuthenticatedAdminSubscriptionsRoute
  AuthenticatedAdminTasksRoute: typeof AuthenticatedAdminTasksRoute
  AuthenticatedAdminTicketsRoute: typeof AuthenticatedAdminTicketsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminVerificationsRoute: typeof AuthenticatedAdminVerificationsRoute
  AuthenticatedAdminWithdrawalsRoute: typeof AuthenticatedAdminWithdrawalsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminAuditLogsRoute: AuthenticatedAdminAuditLogsRoute,
  AuthenticatedAdminBoostsRoute: AuthenticatedAdminBoostsRoute,
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
  AuthenticatedAdminChatsRoute: AuthenticatedAdminChatsRoute,
  AuthenticatedAdminCommunicationRoute: AuthenticatedAdminCommunicationRoute,
  AuthenticatedAdminDisputesRoute: AuthenticatedAdminDisputesRoute,
  AuthenticatedAdminEarningsRoute: AuthenticatedAdminEarningsRoute,
  AuthenticatedAdminFinancesRoute: AuthenticatedAdminFinancesRoute,
  AuthenticatedAdminInvoiceTemplatesRoute:
    AuthenticatedAdminInvoiceTemplatesRoute,
  AuthenticatedAdminInvoicesRoute: AuthenticatedAdminInvoicesRoute,
  AuthenticatedAdminListingsRoute: AuthenticatedAdminListingsRoute,
  AuthenticatedAdminNewsletterRoute: AuthenticatedAdminNewsletterRoute,
  AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminSecurityLogsRoute: AuthenticatedAdminSecurityLogsRoute,
  AuthenticatedAdminSeoRoute: AuthenticatedAdminSeoRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminStaffRoute: AuthenticatedAdminStaffRoute,
  AuthenticatedAdminSubscriptionsRoute: AuthenticatedAdminSubscriptionsRoute,
  AuthenticatedAdminTasksRoute: AuthenticatedAdminTasksRoute,
  AuthenticatedAdminTicketsRoute: AuthenticatedAdminTicketsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminVerificationsRoute: AuthenticatedAdminVerificationsRoute,
  AuthenticatedAdminWithdrawalsRoute: AuthenticatedAdminWithdrawalsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedSellerRouteChildren {
  AuthenticatedSellerAdsRoute: typeof AuthenticatedSellerAdsRoute
  AuthenticatedSellerAnalyticsRoute: typeof AuthenticatedSellerAnalyticsRoute
  AuthenticatedSellerBoostsRoute: typeof AuthenticatedSellerBoostsRoute
  AuthenticatedSellerCouponsRoute: typeof AuthenticatedSellerCouponsRoute
  AuthenticatedSellerDeliveryRoute: typeof AuthenticatedSellerDeliveryRoute
  AuthenticatedSellerDisputesRoute: typeof AuthenticatedSellerDisputesRoute
  AuthenticatedSellerEarningsRoute: typeof AuthenticatedSellerEarningsRoute
  AuthenticatedSellerListingsRoute: typeof AuthenticatedSellerListingsRoute
  AuthenticatedSellerMessagesRoute: typeof AuthenticatedSellerMessagesRoute
  AuthenticatedSellerNotificationsRoute: typeof AuthenticatedSellerNotificationsRoute
  AuthenticatedSellerOrdersRoute: typeof AuthenticatedSellerOrdersRoute
  AuthenticatedSellerReviewsRoute: typeof AuthenticatedSellerReviewsRoute
  AuthenticatedSellerSecurityRoute: typeof AuthenticatedSellerSecurityRoute
  AuthenticatedSellerSettingsRoute: typeof AuthenticatedSellerSettingsRoute
  AuthenticatedSellerStoreRoute: typeof AuthenticatedSellerStoreRoute
  AuthenticatedSellerSupportRoute: typeof AuthenticatedSellerSupportRoute
  AuthenticatedSellerTransactionsRoute: typeof AuthenticatedSellerTransactionsRoute
  AuthenticatedSellerVerificationRoute: typeof AuthenticatedSellerVerificationRoute
  AuthenticatedSellerWalletRoute: typeof AuthenticatedSellerWalletRoute
  AuthenticatedSellerWithdrawalsRoute: typeof AuthenticatedSellerWithdrawalsRoute
  AuthenticatedSellerIndexRoute: typeof AuthenticatedSellerIndexRoute
  AuthenticatedSellerSubscriptionPaymentRoute: typeof AuthenticatedSellerSubscriptionPaymentRoute
  AuthenticatedSellerSubscriptionIndexRoute: typeof AuthenticatedSellerSubscriptionIndexRoute
}

const AuthenticatedSellerRouteChildren: AuthenticatedSellerRouteChildren = {
  AuthenticatedSellerAdsRoute: AuthenticatedSellerAdsRoute,
  AuthenticatedSellerAnalyticsRoute: AuthenticatedSellerAnalyticsRoute,
  AuthenticatedSellerBoostsRoute: AuthenticatedSellerBoostsRoute,
  AuthenticatedSellerCouponsRoute: AuthenticatedSellerCouponsRoute,
  AuthenticatedSellerDeliveryRoute: AuthenticatedSellerDeliveryRoute,
  AuthenticatedSellerDisputesRoute: AuthenticatedSellerDisputesRoute,
  AuthenticatedSellerEarningsRoute: AuthenticatedSellerEarningsRoute,
  AuthenticatedSellerListingsRoute: AuthenticatedSellerListingsRoute,
  AuthenticatedSellerMessagesRoute: AuthenticatedSellerMessagesRoute,
  AuthenticatedSellerNotificationsRoute: AuthenticatedSellerNotificationsRoute,
  AuthenticatedSellerOrdersRoute: AuthenticatedSellerOrdersRoute,
  AuthenticatedSellerReviewsRoute: AuthenticatedSellerReviewsRoute,
  AuthenticatedSellerSecurityRoute: AuthenticatedSellerSecurityRoute,
  AuthenticatedSellerSettingsRoute: AuthenticatedSellerSettingsRoute,
  AuthenticatedSellerStoreRoute: AuthenticatedSellerStoreRoute,
  AuthenticatedSellerSupportRoute: AuthenticatedSellerSupportRoute,
  AuthenticatedSellerTransactionsRoute: AuthenticatedSellerTransactionsRoute,
  AuthenticatedSellerVerificationRoute: AuthenticatedSellerVerificationRoute,
  AuthenticatedSellerWalletRoute: AuthenticatedSellerWalletRoute,
  AuthenticatedSellerWithdrawalsRoute: AuthenticatedSellerWithdrawalsRoute,
  AuthenticatedSellerIndexRoute: AuthenticatedSellerIndexRoute,
  AuthenticatedSellerSubscriptionPaymentRoute:
    AuthenticatedSellerSubscriptionPaymentRoute,
  AuthenticatedSellerSubscriptionIndexRoute:
    AuthenticatedSellerSubscriptionIndexRoute,
}

const AuthenticatedSellerRouteWithChildren =
  AuthenticatedSellerRoute._addFileChildren(AuthenticatedSellerRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedBannedRoute: typeof AuthenticatedBannedRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedSellerRoute: typeof AuthenticatedSellerRouteWithChildren
  AuthenticatedSuspendedRoute: typeof AuthenticatedSuspendedRoute
  AuthenticatedCheckoutPaymentRoute: typeof AuthenticatedCheckoutPaymentRoute
  AuthenticatedCheckoutVerifyPaymentRoute: typeof AuthenticatedCheckoutVerifyPaymentRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedBannedRoute: AuthenticatedBannedRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedSellerRoute: AuthenticatedSellerRouteWithChildren,
  AuthenticatedSuspendedRoute: AuthenticatedSuspendedRoute,
  AuthenticatedCheckoutPaymentRoute: AuthenticatedCheckoutPaymentRoute,
  AuthenticatedCheckoutVerifyPaymentRoute:
    AuthenticatedCheckoutVerifyPaymentRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface CoachingRouteChildren {
  CoachingIdRoute: typeof CoachingIdRoute
}

const CoachingRouteChildren: CoachingRouteChildren = {
  CoachingIdRoute: CoachingIdRoute,
}

const CoachingRouteWithChildren = CoachingRoute._addFileChildren(
  CoachingRouteChildren,
)

interface GameBuddiesRouteChildren {
  GameBuddiesIdRoute: typeof GameBuddiesIdRoute
}

const GameBuddiesRouteChildren: GameBuddiesRouteChildren = {
  GameBuddiesIdRoute: GameBuddiesIdRoute,
}

const GameBuddiesRouteWithChildren = GameBuddiesRoute._addFileChildren(
  GameBuddiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  BecomeCoachRoute: BecomeCoachRoute,
  BecomeGameBuddyRoute: BecomeGameBuddyRoute,
  BlogRoute: BlogRoute,
  BrowseRoute: BrowseRoute,
  CareersRoute: CareersRoute,
  CategoriesRoute: CategoriesRoute,
  CoachingRoute: CoachingRouteWithChildren,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GameBuddiesRoute: GameBuddiesRouteWithChildren,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRoute,
  PagesRoute: PagesRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SellerPanelRoute: SellerPanelRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeamLoginRoute: TeamLoginRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ServerTrackDurationRoute: ServerTrackDurationRoute,
  AccountVerifyPhoneRoute: AccountVerifyPhoneRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthVerifiedRoute: AuthVerifiedRoute,
  CategorySlugRoute: CategorySlugRoute,
  ProductIdRoute: ProductIdRoute,
  VerifyInvoiceNumberRoute: VerifyInvoiceNumberRoute,
  AccountIndexRoute: AccountIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
